// Stage 3 of the pipeline: byte-patch the game's own Wwise SoundBanks, swapping in the .wem files
// produced by BatchEncoder in place of the original English-language audio, matched by SID via
// data/FINAL_lektor_mapping.csv + build/FULL_BATCH_wem_mapping.csv.
// See README.md "Quick start" and docs/architecture.md for the full pipeline and why this works
// the way it does (FBulkDataMapEntry / .ubulk splice).
using System.Diagnostics;
using System.Text;
using System.Text.Json;
using CUE4Parse.FileProvider;
using CUE4Parse.UE4.Versions;
using CUE4Parse.Compression;
using CUE4Parse.MappingsProvider.Usmap;
using CUE4Parse.UE4.Assets;
using CUE4Parse.UE4.Assets.Exports.Wwise;
using CUE4Parse.UE4.Wwise;
using Serilog;

Log.Logger = new LoggerConfiguration().MinimumLevel.Warning().WriteTo.Console().CreateLogger();

var repoRoot = Config.FindRepoRoot();
var config = Config.Load(repoRoot);

// Language variant: "EN" (default) patches the English(US) slots, "UA" the Ukrainian(UA) ones.
// Never install both variants at once — see README.md.
string variant = args.Length > 0 ? args[0].ToUpperInvariant() : "EN";
if (variant != "EN" && variant != "UA")
    throw new ArgumentException($"Unknown variant '{args[0]}' — expected EN or UA.");
string langKey = variant == "UA" ? "Ukrainian" : "English";
string mediaIdCol = variant == "UA" ? "UkrainianMediaId" : "EnglishMediaId";
Console.WriteLine($"Variant: {variant} (patching {langKey} slots)");

string gameDir = config.GameDir;
string usmapPath = config.Usmap;
string wemDir = Path.Combine(repoRoot, "WwiseProject", "full_batch_wem", "Windows");
string buildDir = Path.Combine(repoRoot, "build");
string outputRoot = Path.Combine(buildDir, $"ModOutput_{variant}");
string mappingCsv = Path.Combine(buildDir, "FULL_BATCH_wem_mapping.csv");
string reportCsv = Path.Combine(buildDir, $"FULL_PATCH_report_{variant}.csv");
Directory.CreateDirectory(buildDir);

if (!File.Exists(config.OodleDllPath))
    throw new FileNotFoundException(
        $"Oodle DLL not found at '{config.OodleDllPath}'. Set oodleDllPath in config.json — " +
        "see README.md for where to obtain oo2core_9_win64.dll.");
OodleHelper.Initialize(config.OodleDllPath);

var versions = new VersionContainer(EGame.GAME_UE5_5);
var provider = new DefaultFileProvider(gameDir, SearchOption.AllDirectories, isCaseInsensitive: true, versions);
provider.MappingsContainer = new FileUsmapTypeMappingsProvider(usmapPath);
provider.Initialize();
provider.SubmitKey(new CUE4Parse.UE4.Objects.Core.Misc.FGuid(0), new CUE4Parse.Encryption.Aes.FAesKey("0x0000000000000000000000000000000000000000000000000000000000000000"));
provider.Mount();
Console.WriteLine($"Mounted. Total files: {provider.Files.Count}");

// Build suffix index: for every VO_*.uasset path, index every suffix starting at each underscore boundary -> full path.
// (Event filenames are VO_<unknown-actor-prefix>_<SID>.uasset, so we need suffix matching to find them by SID alone.)
var suffixIndex = new Dictionary<string, string>(StringComparer.Ordinal);
int ambiguous = 0;
foreach (var path in provider.Files.Keys)
{
    if (!path.EndsWith(".uasset", StringComparison.OrdinalIgnoreCase)) continue;
    var fname = Path.GetFileNameWithoutExtension(path);
    if (!fname.StartsWith("VO_", StringComparison.Ordinal)) continue;
    var rest = fname[3..];
    int idx = 0;
    while (true)
    {
        if (!suffixIndex.TryAdd(rest[idx..], path)) ambiguous++;
        int next = rest.IndexOf('_', idx);
        if (next < 0) break;
        idx = next + 1;
    }
}
Console.WriteLine($"Suffix index built: {suffixIndex.Count} keys ({ambiguous} collisions, first-seen kept).");

if (!File.Exists(mappingCsv))
    throw new FileNotFoundException($"'{mappingCsv}' not found — run BatchEncoder first, it writes this file.");
var rows = ParseCsv(mappingCsv);
Console.WriteLine($"Loaded {rows.Count} rows from {mappingCsv}");

// UA variant: never touch SIDs whose Ukrainian slot is defective in the base game
// (Is41UkrainianMismatch / no byte-verified UA audio) — overwriting them can corrupt other
// dialogue. List generated by make_build_inputs.py. See docs/PUŁAPKI.md point 10.
var uaSkip = new HashSet<string>(StringComparer.Ordinal);
if (variant == "UA")
{
    string uaSkipPath = Path.Combine(buildDir, "UA_SKIP_SIDS.txt");
    if (!File.Exists(uaSkipPath))
        throw new FileNotFoundException($"'{uaSkipPath}' not found — rerun make_build_inputs.py, the UA variant requires it.");
    foreach (var line in File.ReadAllLines(uaSkipPath))
        if (!string.IsNullOrWhiteSpace(line)) uaSkip.Add(line.Trim());
    Console.WriteLine($"UA skip list: {uaSkip.Count} defective-slot SIDs will be left untouched.");
}

int okCount = 0, skipNoUasset = 0, skipNoMedia = 0, skipNoWem = 0, skipNoEntry = 0, skipNoPattern = 0, skipCutscene = 0, skipUaDefect = 0, errCount = 0;
var sw = Stopwatch.StartNew();
using var report = new StreamWriter(reportCsv, false, Encoding.UTF8);
report.WriteLine("SID,Population,Status,Detail");

// Hard cutscene guard (see docs/JAK-AKTUALIZOWAC-I-WDRAZAC.md section 7): the cutscene pipeline
// is broken/out of scope, never patch those assets.
bool IsCutscene(string sid, string uassetPath) =>
    sid.StartsWith("C_", StringComparison.Ordinal) ||
    uassetPath.Contains("/Cutscenes/", StringComparison.OrdinalIgnoreCase);

// Patches one asset: replaces the payload of every (oldOffset, oldSize) bulk-data region in the
// .ubulk with its new WEM bytes, and rewrites the BulkDataMap in the .uasset accordingly
// (SerialSize of each replaced entry, SerialOffset of everything that shifts).
// Returns null on success, otherwise a status string for the report.
string? PatchAsset(string sid, string population, string uassetPath, IoPackage iopkg,
    List<(ulong OldOffset, ulong OldSize, byte[] NewBytes)> targets)
{
    // Map each target to its BulkDataMap entry.
    var entryIdxs = new int[targets.Count];
    for (int t = 0; t < targets.Count; t++)
    {
        int entryIdx = -1;
        for (int i = 0; i < iopkg.BulkDataMap.Length; i++)
        {
            if (iopkg.BulkDataMap[i].SerialOffset == targets[t].OldOffset && iopkg.BulkDataMap[i].SerialSize == targets[t].OldSize)
            {
                entryIdx = i;
                break;
            }
        }
        if (entryIdx < 0) return "NoBulkDataMapEntry";
        entryIdxs[t] = entryIdx;
    }

    byte[] uassetBytes = provider.SaveAsset(uassetPath);
    string ubulkPath = Path.ChangeExtension(uassetPath, ".ubulk");
    byte[] ubulkBytes = provider.SaveAsset(ubulkPath);

    // The 32-byte BulkDataMap entries are contiguous in the .uasset; locate the array once via
    // the first target's encoded entry, then address every entry as baseOffset + idx * 32.
    byte[] pattern = EncodeEntry(iopkg.BulkDataMap[entryIdxs[0]]);
    int pos = IndexOf(uassetBytes, pattern);
    if (pos < 0) return "NoBytePattern";
    int baseOffset = pos - entryIdxs[0] * 32;
    // Integrity check: every entry must sit where the contiguous layout predicts.
    for (int j = 0; j < iopkg.BulkDataMap.Length; j++)
    {
        int posJ = baseOffset + j * 32;
        if (posJ < 0 || posJ + 32 > uassetBytes.Length) return "NoBytePattern";
        var expect = EncodeEntry(iopkg.BulkDataMap[j]);
        for (int b = 0; b < 32; b++)
            if (uassetBytes[posJ + b] != expect[b]) return "NoBytePattern";
    }

    // Splice all regions in ascending offset order (they must not overlap).
    var ordered = targets.Select((tg, i) => (tg.OldOffset, tg.OldSize, tg.NewBytes, EntryIdx: entryIdxs[i]))
                         .OrderBy(x => x.OldOffset).ToList();
    for (int i = 1; i < ordered.Count; i++)
        if (ordered[i - 1].OldOffset + ordered[i - 1].OldSize > ordered[i].OldOffset) return "OverlappingRegions";

    long totalDelta = ordered.Sum(x => x.NewBytes.Length - (long)x.OldSize);
    var newUbulk = new byte[ubulkBytes.Length + totalDelta];
    long src = 0, dst = 0;
    foreach (var x in ordered)
    {
        long copy = (long)x.OldOffset - src;
        Array.Copy(ubulkBytes, src, newUbulk, dst, copy);
        src += copy; dst += copy;
        Array.Copy(x.NewBytes, 0, newUbulk, dst, x.NewBytes.Length);
        src += (long)x.OldSize; dst += x.NewBytes.Length;
    }
    Array.Copy(ubulkBytes, src, newUbulk, dst, ubulkBytes.Length - src);

    byte[] patchedUasset = (byte[])uassetBytes.Clone();
    foreach (var x in ordered)
        WriteU64LE(patchedUasset, baseOffset + x.EntryIdx * 32 + 16, (ulong)x.NewBytes.Length);
    for (int j = 0; j < iopkg.BulkDataMap.Length; j++)
    {
        // Shift by the summed delta of every replaced region that starts before this entry.
        long shift = ordered.Where(x => x.OldOffset < iopkg.BulkDataMap[j].SerialOffset)
                            .Sum(x => x.NewBytes.Length - (long)x.OldSize);
        if (shift == 0) continue;
        WriteU64LE(patchedUasset, baseOffset + j * 32, (ulong)((long)iopkg.BulkDataMap[j].SerialOffset + shift));
    }

    string outUasset = Path.Combine(outputRoot, uassetPath.Replace('/', Path.DirectorySeparatorChar));
    string outUbulk = Path.Combine(outputRoot, ubulkPath.Replace('/', Path.DirectorySeparatorChar));
    Directory.CreateDirectory(Path.GetDirectoryName(outUasset)!);
    File.WriteAllBytes(outUasset, patchedUasset);
    File.WriteAllBytes(outUbulk, newUbulk);
    return null;
}

for (int rowIdx = 0; rowIdx < rows.Count; rowIdx++)
{
    var row = rows[rowIdx];
    string sid = row["SID"];
    string mediaIdStr = row[mediaIdCol];
    string wemName = row["WemName"];

    try
    {
        if (uaSkip.Contains(sid))
        {
            skipUaDefect++;
            report.WriteLine($"\"{sid}\",MAIN,UaDefectiveSlotSkip,");
            continue;
        }
        if (!suffixIndex.TryGetValue(sid, out var uassetPath))
        {
            skipNoUasset++;
            report.WriteLine($"\"{sid}\",MAIN,NoUasset,");
            continue;
        }
        if (IsCutscene(sid, uassetPath))
        {
            skipCutscene++;
            report.WriteLine($"\"{sid}\",MAIN,CutsceneGuard,{uassetPath}");
            continue;
        }

        string wemPath = Path.Combine(wemDir, wemName);
        if (!File.Exists(wemPath))
        {
            skipNoWem++;
            report.WriteLine($"\"{sid}\",MAIN,NoWem,{wemPath}");
            continue;
        }
        byte[] newWemBytes = File.ReadAllBytes(wemPath);

        var pkg = provider.LoadPackage(uassetPath);
        var iopkg = (IoPackage)pkg;
        var akEvent = pkg.GetExports().OfType<UAkAudioEvent>().FirstOrDefault();
        if (akEvent?.EventCookedData == null)
        {
            skipNoMedia++;
            report.WriteLine($"\"{sid}\",MAIN,NoAkEvent,{uassetPath}");
            continue;
        }

        FWwiseMediaCookedData? targetMedia = null;
        bool foreignSid = false;
        foreach (var langEntry in akEvent.EventCookedData.Value.EventLanguageMap)
        {
            if (langEntry.Value == null) continue;
            if (!langEntry.Key.LanguageName.Text.Contains(langKey, StringComparison.OrdinalIgnoreCase)) continue;
            foreach (var media in langEntry.Value.Value.Media)
            {
                var baseName = media.DebugName.Text.Contains('\\') ? media.DebugName.Text[(media.DebugName.Text.LastIndexOf('\\') + 1)..] : media.DebugName.Text;
                if (!baseName.StartsWith("VO_", StringComparison.OrdinalIgnoreCase)) continue;
                if (media.MediaId.ToString() != mediaIdStr) continue;
                // Foreign-SID guard (docs/PUŁAPKI.md point 10): in 42 events the Ukrainian media
                // entry carries a DebugName belonging to a different SID — overwriting it would
                // break that other dialogue. Refuse to patch such entries.
                if (!baseName.Contains(sid, StringComparison.OrdinalIgnoreCase))
                {
                    foreignSid = true;
                    continue;
                }
                targetMedia = media;
                break;
            }
            if (targetMedia != null) break;
        }

        if (targetMedia == null || targetMedia.Value.PackagedFile?.BulkData?.WemFile is not FBulkDataDeferredByteData wemFile)
        {
            skipNoMedia++;
            report.WriteLine($"\"{sid}\",MAIN,{(foreignSid ? "ForeignSidGuard" : "NoMediaMatch")},{uassetPath}");
            continue;
        }

        string? status = PatchAsset(sid, "MAIN", uassetPath, iopkg,
            [((ulong)wemFile.BulkData.Header.OffsetInFile, wemFile.BulkData.Header.SizeOnDisk, newWemBytes)]);
        if (status != null)
        {
            if (status == "NoBulkDataMapEntry") skipNoEntry++; else skipNoPattern++;
            report.WriteLine($"\"{sid}\",MAIN,{status},{uassetPath}");
            continue;
        }

        okCount++;
        report.WriteLine($"\"{sid}\",MAIN,OK,");
    }
    catch (Exception ex)
    {
        errCount++;
        report.WriteLine($"\"{sid}\",MAIN,Error,\"{ex.Message.Replace("\"", "'")}\"");
    }

    if ((rowIdx + 1) % 500 == 0)
    {
        Console.WriteLine($"Progress: {rowIdx + 1}/{rows.Count} | ok={okCount} noUasset={skipNoUasset} noMedia={skipNoMedia} noWem={skipNoWem} noEntry={skipNoEntry} noPattern={skipNoPattern} err={errCount} | {sw.Elapsed}");
    }
}

// === Phase 2: EXTRA (SwitchContainer chatter) + RECOVERED populations ===
// These lists (from make_build_inputs.py) carry no MediaIds — the targets are discovered from
// the asset itself: every English-language VO_ media whose DebugName references the SID, in both
// Media[] and SwitchContainerLeaves[].Media[] (see docs/PUŁAPKI.md points 1 and 10).
foreach (var listName in new[] { "PATCH_LIST_EXTRA.csv", "PATCH_LIST_RECOVERED.csv" })
{
    string listPath = Path.Combine(buildDir, listName);
    if (!File.Exists(listPath))
    {
        Console.WriteLine($"{listName} not found — skipping this population.");
        continue;
    }
    string population = listName.Contains("EXTRA") ? "EXTRA" : "RECOVERED";
    var listRows = ParseCsv(listPath);
    Console.WriteLine($"\n=== {population}: {listRows.Count} rows from {listPath} ===");

    foreach (var row in listRows)
    {
        string sid = row["SID"];
        string wemName = row["WemName"];
        try
        {
            if (uaSkip.Contains(sid))
            {
                skipUaDefect++;
                report.WriteLine($"\"{sid}\",{population},UaDefectiveSlotSkip,");
                continue;
            }
            if (!suffixIndex.TryGetValue(sid, out var uassetPath))
            {
                skipNoUasset++;
                report.WriteLine($"\"{sid}\",{population},NoUasset,");
                continue;
            }
            if (IsCutscene(sid, uassetPath))
            {
                skipCutscene++;
                report.WriteLine($"\"{sid}\",{population},CutsceneGuard,{uassetPath}");
                continue;
            }

            string wemPath = Path.Combine(wemDir, wemName);
            if (!File.Exists(wemPath))
            {
                skipNoWem++;
                report.WriteLine($"\"{sid}\",{population},NoWem,{wemPath}");
                continue;
            }
            byte[] newWemBytes = File.ReadAllBytes(wemPath);

            var pkg = provider.LoadPackage(uassetPath);
            var iopkg = (IoPackage)pkg;
            var akEvent = pkg.GetExports().OfType<UAkAudioEvent>().FirstOrDefault();
            if (akEvent?.EventCookedData == null)
            {
                skipNoMedia++;
                report.WriteLine($"\"{sid}\",{population},NoAkEvent,{uassetPath}");
                continue;
            }

            // Collect every English VO_ media that belongs to this SID (guards against the
            // wrong-SID media defect, PUŁAPKI.md point 10).
            var targets = new List<(ulong, ulong, byte[])>();
            var seenOffsets = new HashSet<ulong>();
            void Collect(FWwiseMediaCookedData media)
            {
                var baseName = media.DebugName.Text.Contains('\\') ? media.DebugName.Text[(media.DebugName.Text.LastIndexOf('\\') + 1)..] : media.DebugName.Text;
                if (!baseName.StartsWith("VO_", StringComparison.OrdinalIgnoreCase)) return;
                if (!baseName.Contains(sid, StringComparison.OrdinalIgnoreCase)) return;
                if (media.PackagedFile?.BulkData?.WemFile is not FBulkDataDeferredByteData wf) return;
                if (!seenOffsets.Add((ulong)wf.BulkData.Header.OffsetInFile)) return;
                targets.Add(((ulong)wf.BulkData.Header.OffsetInFile, wf.BulkData.Header.SizeOnDisk, newWemBytes));
            }
            foreach (var langEntry in akEvent.EventCookedData.Value.EventLanguageMap)
            {
                if (langEntry.Value == null) continue;
                if (!langEntry.Key.LanguageName.Text.Contains(langKey, StringComparison.OrdinalIgnoreCase)) continue;
                foreach (var media in langEntry.Value.Value.Media)
                    Collect(media);
                if (langEntry.Value.Value.SwitchContainerLeaves != null)
                    foreach (var leaf in langEntry.Value.Value.SwitchContainerLeaves)
                        foreach (var media in leaf.Media)
                            Collect(media);
            }

            if (targets.Count == 0)
            {
                skipNoMedia++;
                report.WriteLine($"\"{sid}\",{population},NoMediaMatch,{uassetPath}");
                continue;
            }

            string? status = PatchAsset(sid, population, uassetPath, iopkg, targets);
            if (status != null)
            {
                if (status == "NoBulkDataMapEntry") skipNoEntry++; else skipNoPattern++;
                report.WriteLine($"\"{sid}\",{population},{status},{uassetPath}");
                continue;
            }

            okCount++;
            report.WriteLine($"\"{sid}\",{population},OK,{targets.Count} media");
        }
        catch (Exception ex)
        {
            errCount++;
            report.WriteLine($"\"{sid}\",{population},Error,\"{ex.Message.Replace("\"", "'")}\"");
        }
    }
    Console.WriteLine($"{population} done | ok(total)={okCount} noUasset={skipNoUasset} noMedia={skipNoMedia} noWem={skipNoWem} err={errCount}");
}

Console.WriteLine("\n=== FINAL SUMMARY ===");
Console.WriteLine($"Total rows: {rows.Count}");
Console.WriteLine($"OK (patched): {okCount}");
Console.WriteLine($"Skip - no uasset resolved: {skipNoUasset}");
Console.WriteLine($"Skip - no media match: {skipNoMedia}");
Console.WriteLine($"Skip - no wem file: {skipNoWem}");
Console.WriteLine($"Skip - no BulkDataMap entry: {skipNoEntry}");
Console.WriteLine($"Skip - no byte pattern found: {skipNoPattern}");
Console.WriteLine($"Skip - cutscene guard: {skipCutscene}");
Console.WriteLine($"Skip - defective UA slot: {skipUaDefect}");
Console.WriteLine($"Errors: {errCount}");
Console.WriteLine($"Elapsed: {sw.Elapsed}");
Console.WriteLine($"Report written to: {reportCsv}");
Console.WriteLine($"Patched content written under: {outputRoot}");
Console.WriteLine("Next step: repack outputRoot with UnrealReZen (see README.md).");

static byte[] EncodeEntry(CUE4Parse.UE4.IO.Objects.FBulkDataMapEntry e)
{
    var buf = new byte[32];
    WriteU64LE(buf, 0, e.SerialOffset);
    WriteU64LE(buf, 8, e.DuplicateSerialOffset);
    WriteU64LE(buf, 16, e.SerialSize);
    WriteU32LE(buf, 24, e.Flags);
    buf[28] = e.CookedIndex.Value;
    return buf;
}

static void WriteU64LE(byte[] buf, int offset, ulong value)
{
    for (int i = 0; i < 8; i++) buf[offset + i] = (byte)(value >> (8 * i));
}

static void WriteU32LE(byte[] buf, int offset, uint value)
{
    for (int i = 0; i < 4; i++) buf[offset + i] = (byte)(value >> (8 * i));
}

static int IndexOf(byte[] haystack, byte[] needle)
{
    for (int i = 0; i <= haystack.Length - needle.Length; i++)
    {
        bool match = true;
        for (int j = 0; j < needle.Length; j++)
        {
            if (haystack[i + j] != needle[j]) { match = false; break; }
        }
        if (match) return i;
    }
    return -1;
}

static List<Dictionary<string, string>> ParseCsv(string path)
{
    var lines = File.ReadAllLines(path, Encoding.UTF8);
    var header = SplitCsvLine(lines[0]);
    var result = new List<Dictionary<string, string>>();
    for (int i = 1; i < lines.Length; i++)
    {
        if (string.IsNullOrWhiteSpace(lines[i])) continue;
        var fields = SplitCsvLine(lines[i]);
        var dict = new Dictionary<string, string>();
        for (int j = 0; j < header.Count && j < fields.Count; j++)
            dict[header[j].Trim('"')] = fields[j];
        result.Add(dict);
    }
    return result;
}

static List<string> SplitCsvLine(string line)
{
    var fields = new List<string>();
    var sb = new StringBuilder();
    bool inQuotes = false;
    for (int i = 0; i < line.Length; i++)
    {
        char c = line[i];
        if (inQuotes)
        {
            if (c == '"')
            {
                if (i + 1 < line.Length && line[i + 1] == '"') { sb.Append('"'); i++; }
                else inQuotes = false;
            }
            else sb.Append(c);
        }
        else
        {
            if (c == '"') inQuotes = true;
            else if (c == ',') { fields.Add(sb.ToString()); sb.Clear(); }
            else sb.Append(c);
        }
    }
    fields.Add(sb.ToString());
    return fields;
}

// Shared config type/loader — duplicated verbatim in BatchEncoder/Program.cs so each tool stays a
// single self-contained file. See config.example.json for the full field list and comments.
record Config(string GameDir, string Usmap, string WwiseConsole, string Ffmpeg, string GameReaderAudioDir, string OodleDllPath)
{
    public static string FindRepoRoot()
    {
        var d = new DirectoryInfo(AppContext.BaseDirectory);
        while (d != null)
        {
            if (File.Exists(Path.Combine(d.FullName, "config.json"))) return d.FullName;
            d = d.Parent;
        }
        throw new FileNotFoundException(
            "config.json not found above " + AppContext.BaseDirectory +
            ". Copy config.example.json to config.json in the repo root and fill in your local paths.");
    }

    public static Config Load(string repoRoot)
    {
        var json = File.ReadAllText(Path.Combine(repoRoot, "config.json"));
        var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        return JsonSerializer.Deserialize<Config>(json, opts)
            ?? throw new InvalidDataException("config.json did not parse to a valid config object.");
    }
}
